
package academia_conexao;

public class frmAcademia extends javax.swing.JFrame {

    /**
     * Creates new form frmAcademia
     */
    public frmAcademia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNovoAluno = new javax.swing.JButton();
        btnNovoProf = new javax.swing.JButton();
        btnNovoExerc = new javax.swing.JButton();
        btnNovoMens = new javax.swing.JButton();
        btnNovotreinos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        btnNovoAluno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNovoAluno.setText("Alunos");
        btnNovoAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoAlunoActionPerformed(evt);
            }
        });

        btnNovoProf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNovoProf.setText("Professores");
        btnNovoProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoProfActionPerformed(evt);
            }
        });

        btnNovoExerc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNovoExerc.setText("Exercicios");
        btnNovoExerc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoExercActionPerformed(evt);
            }
        });

        btnNovoMens.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNovoMens.setText("Mensalidades");
        btnNovoMens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoMensActionPerformed(evt);
            }
        });

        btnNovotreinos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNovotreinos.setText("Treinos");
        btnNovotreinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovotreinosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNovotreinos)
                        .addGap(18, 18, 18)
                        .addComponent(btnNovoMens)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNovoAluno)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(btnNovoProf)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(btnNovoExerc)
                        .addGap(28, 28, 28))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(155, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovoAluno)
                    .addComponent(btnNovoProf)
                    .addComponent(btnNovoExerc))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovotreinos)
                    .addComponent(btnNovoMens))
                .addGap(148, 148, 148))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoAlunoActionPerformed
        frmAluno a = new frmAluno();
        a.setVisible(true);
    }//GEN-LAST:event_btnNovoAlunoActionPerformed

    private void btnNovoProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoProfActionPerformed
        frmProfessor np = new frmProfessor();
        np.setVisible(true);
    }//GEN-LAST:event_btnNovoProfActionPerformed

    private void btnNovoExercActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoExercActionPerformed
        frmExercicio ne = new frmExercicio();
        ne.setVisible(true);
    }//GEN-LAST:event_btnNovoExercActionPerformed

    private void btnNovotreinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovotreinosActionPerformed
        frmTreino nt = new frmTreino();
        nt.setVisible(true);
    }//GEN-LAST:event_btnNovotreinosActionPerformed

    private void btnNovoMensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoMensActionPerformed
        frmMensalidade m = new frmMensalidade();
        m.setVisible(true);
    }//GEN-LAST:event_btnNovoMensActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAcademia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAcademia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAcademia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAcademia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAcademia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNovoAluno;
    private javax.swing.JButton btnNovoExerc;
    private javax.swing.JButton btnNovoMens;
    private javax.swing.JButton btnNovoProf;
    private javax.swing.JButton btnNovotreinos;
    // End of variables declaration//GEN-END:variables
}
